name: 刷步数

on:
  schedule:
    - cron: '0 0,1,8,9 * * *'   # UTC时间 0,1,8,9点（北京时间 8,9,16,17点）
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          pip install requests
          pip install pycryptodome
          
      - name: 运行刷步数脚本
        env:
          CONFIG: ${{ secrets.CONFIG }}
          PAT: ${{ secrets.PAT }}
        run: |
          python main.py